image build and push

diff --git a/.github/workflows/openshift.yml b/.github/workflows/openshift.yml
--- a/.github/workflows/openshift.yml
+++ b/.github/workflows/openshift.yml
@@ -1,27 +1,18 @@
 name: OpenShift
 
 env:
-  # ⬇️ EDIT with your registry and registry path.
-  REGISTRY: docker.pkg.github.com/burrsutter/nodegithubhaikus
-  # ⬇️ EDIT with your registry username.
-  REGISTRY_USER: burrsutter
-  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
-
-  # ⬇️ EDIT to log into your OpenShift cluster and set up the context.
-  # See https://github.com/redhat-actions/oc-login#readme for how to retrieve these values.
+  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
+  REGISTRY_USER: ${{ github.actor }}
+  REGISTRY_PASSWORD: ${{ github.token }}
+  APP_NAME: haikus
+  IMAGE_TAGS: latest ${{ github.sha }}
+  
   OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
   OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
 
-  # ⬇️ EDIT with any additional port your application should expose.
-  # By default, oc new-app action creates a service to the image's lowest numeric exposed port.
   APP_PORT: "3000"
 
-  # ⬇️ EDIT if you wish to set the kube context's namespace after login. Leave blank to use the default namespace.
   OPENSHIFT_NAMESPACE: "burrzinga-stage"
-
-  # If you wish to manually provide the APP_NAME and TAG, set them here, otherwise they will be auto-detected.
-  APP_NAME: "haikus"
-  TAG: v1 ${{ github.sha }}
 
 on:
   # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows
@@ -30,8 +21,8 @@ on:
     branches: [ main ]
 
 jobs:
-  openshift-ci-cd:
-    name: Build and deploy to OpenShift via S2I
+  build-and-push:
+    name: Build and push to github container registry
     runs-on: ubuntu-18.04
     environment: production
 
@@ -41,36 +32,27 @@ jobs:
 
     steps:
     - name: Checkout
+      id: checkout
       uses: actions/checkout@v2
-
-    - name: Determine app name
-      if: env.APP_NAME == ''
-      run: |
-        echo "APP_NAME=$(basename $PWD)" | tee -a $GITHUB_ENV
-
-    - name: Determine tag
-      if: env.TAG == ''
-      run: |
-        echo "TAG=${GITHUB_SHA::7}" | tee -a $GITHUB_ENV
-
-   # https://github.com/marketplace/actions/source-to-image-build#readme
-    - name: Build from Source via S2I
+    
+   # https://github.com/redhat-actions/s2i-build#readme
+    - name: S2I Build
       id: build_image
       uses: redhat-actions/s2i-build@v2
       with:
         path_context: '.'
         builder_image: 'registry.access.redhat.com/ubi7/nodejs-14'
         image: ${{ env.APP_NAME }}
-        tags: ${{ env.TAG }}
+        tags: ${{ env.IMAGE_TAGS }}
         
     # https://github.com/redhat-actions/push-to-registry#readme
-    - name: Push to registry
+    - name: Push to Registry
       id: push-to-registry
       uses: redhat-actions/push-to-registry@v2
       with:
         image: ${{ steps.build_image.outputs.image }}
         tags: ${{ steps.build_image.outputs.tags }}
-        registry: ${{ env.REGISTRY }}
+        registry: ${{ env.IMAGE_REGISTRY }}
         username: ${{ env.REGISTRY_USER }}
         password: ${{ env.REGISTRY_PASSWORD }}
 
@@ -82,33 +64,33 @@ jobs:
     # as well as many other tools.
 
     # https://github.com/redhat-actions/oc-login#readme
-    - name: Log in to OpenShift
-      uses: redhat-actions/oc-login@v1
-      with:
-        openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
-        openshift_token: ${{ env.OPENSHIFT_TOKEN }}
-        insecure_skip_tls_verify: true
-        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
+    # - name: Log in to OpenShift
+    #  uses: redhat-actions/oc-login@v1
+    #  with:
+    #    openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
+    #    openshift_token: ${{ env.OPENSHIFT_TOKEN }}
+    #    insecure_skip_tls_verify: true
+    #    namespace: ${{ env.OPENSHIFT_NAMESPACE }}
 
     # This step should create a deployment, service, and route to run your app and expose it to the internet.
     # https://github.com/redhat-actions/oc-new-app#readme
-    - name: Create and expose app
-      id: deploy-and-expose
-      uses: redhat-actions/oc-new-app@v1
-      with:
-        app_name: ${{ env.APP_NAME }}
-        image: ${{ steps.push-to-registry.outputs.registry-path }}
-        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
-        port: ${{ env.APP_PORT }}
+    # - name: Create and expose app
+    #  id: deploy-and-expose
+    #  uses: redhat-actions/oc-new-app@v1
+    #  with:
+    #    app_name: ${{ env.APP_NAME }}
+    #    image: ${{ steps.push-to-registry.outputs.registry-path }}
+    #    namespace: ${{ env.OPENSHIFT_NAMESPACE }}
+    #    port: ${{ env.APP_PORT }}
 
-    - name: View application route
-      run: |
-        [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
-        echo "======================== Your application is available at: ========================"
-        echo ${{ env.ROUTE }}
-        echo "==================================================================================="
-        echo
-        echo "Your app can be taken down with: \"oc delete all --selector='${{ env.SELECTOR }}'\""
-      env:
-        ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
-        SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
+    # - name: View application route
+    #  run: |
+    #    [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
+    #    echo "======================== Your application is available at: ========================"
+    #    echo ${{ env.ROUTE }}
+    #    echo "==================================================================================="
+    #    echo
+    #    echo "Your app can be taken down with: \"oc delete all --selector='${{ env.SELECTOR }}'\""
+    #  env:
+    #    ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
+    #    SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
